name: build
on: [push]

env:
    VERSION_PREFIX: "6.3.1"

jobs:
    build:
        runs-on: [self-hosted, AWS, Linux]

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - run: dotnet restore D2L.LaunchDarkly.ServerSdk.sln
          - run: dotnet test --configuration Release D2L.LaunchDarkly.ServerSdk.sln
          - run: dotnet pack --configuration Release D2L.LaunchDarkly.ServerSdk.sln
